version: 2
jobs:
    test-python37:
        docker:
            - image: python:3.7-alpine
        steps:
            - checkout
            - run:
                name: Install packages
                command: apk add gcc musl-dev git
            - run:
                name: Install Python packages
                command: pip install -r requirements.txt
            - run:
                name: Run tests
                command: tox -e 'py37'

    test-python38:
        docker:
            - image: python:3.8-rc-alpine
        steps:
            - checkout
            - run:
                name: Install packages
                command: apk add gcc musl-dev git
            - run:
                name: Install Python packages
                command: pip install -r requirements.txt
            - run:
                name: Run tests
                command: tox -e 'py38'

    analysis:
        docker:
            - image: python:3.7-alpine
        steps:
            - checkout
            - run:
                name: Install packages
                command: apk add gcc musl-dev git
            - run:
                name: Install Python packages
                command: pip install -r requirements.txt
            - run:
                name: Verify formatting
                command: python setup.py format_verify
            - run:
                name: Lint code
                command: python setup.py lint


workflows:
    version: 2
    build:
        jobs:
            - test-python37
            - test-python38
            - analysis
